import Head from "next/head";
import { ImIcoMoon } from "react-icons/im";
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import udoka from "../public/udoka.png";
import ecommerce from "../public/ecommerce.png";
import memory from "../public/memory.png";
import CountriesAppImage from "../public/countries.png";
import Pokemon from "../public/pokedex2.png";
import chat from "../public/chat.png";
import sd from "../public/sd.png";
import db from "../public/db.png";
import devops from "../public/devops.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">U U</h1>
            <ul className="flex items-center">
              <li>
                <ImIcoMoon
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-2 rounded-md ml-8"
                  href="resume.pdf"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Udoka Udodigwe
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              I design and develop websites for all purposes. Hang on to see the
              services i provide.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/udoka-udodigwe-073872105/"
              target="_blank"
            >
              <AiFillLinkedin className="dark:text-white" />
            </a>
            <a
              href="https://www.instagram.com/skimmer_udy/?hl=en"
              target="_blank"
            >
              <AiFillInstagram className="dark:text-white" />
            </a>
            <a href="https://github.com/Udokailodigwe" target="_blank">
              <AiFillGithub className="dark:text-white" />
            </a>
          </div>
          <div className="relative rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96">
            <Image src={udoka} alt="" layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <p className="text-center text-lg py-2 leading-8 dark:text-gray-200">
              Since i began my journey as a software developer and Database
              Administrator, I have done remote work for agencies and
              collaborated with talanted people to develop softwares and manage
              databases for businesses and consumers.
            </p>
            <p className="text-center text-4xl pt-8 dark:text-white">
              Services
            </p>
            <div className="flex flex-col gap-10 py-5 lg:flex-row lg:flex-wrap">
              <div className="base-1/3 flex-1 text-center shadow p-5 dark:bg-blue-300">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Fullstack Services
                </h3>
                <Image
                  src={sd}
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
                <h3 className="py-4 text-teal-600">Tools</h3>
                <p className="text-gray-800 py-1">Javascript/Typescript</p>
                <p className="text-gray-800 py-1">React/React Native</p>
                <p className="text-gray-800 py-1">Next.js</p>
                <p className="text-gray-800 py-1">Redux Toolkit</p>
                <p className="text-gray-800 py-1">Node.js</p>
                <p className="text-gray-800 py-1">Express.js</p>
                <p className="text-gray-800 py-1">Google Auth</p>
                <p className="text-gray-800 py-1">Passport.js</p>
              </div>
              <div className="base-1/3 flex-1 text-center shadow p-10 dark:bg-blue-300">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Database Services
                </h3>
                <Image
                  src={db}
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
                <h3 className="py-4 text-teal-600">Tools</h3>
                <p className="text-gray-800 py-1">SQL</p>
                <p className="text-gray-800 py-1">No SQL</p>
                <p className="text-gray-800 py-1">Firebase Cloud Storage</p>
              </div>
              <div className="base-1/3 flex-1 text-center shadow p-10 dark:bg-blue-300">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  DevOps Services
                </h3>
                <Image
                  src={devops}
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
                <h3 className="py-4 text-teal-600">Tools</h3>
                <p className="text-gray-800 py-1">CI/CD</p>
                <p className="text-gray-800 py-1">Git</p>
                <p className="text-gray-800 py-1">Docker</p>
                <p className="text-gray-800 py-1">Bash Scripting</p>
                <p className="text-gray-800 py-1">Heroku</p>
                <p className="text-gray-800 py-1">Netlify</p>
                <p className="text-gray-800 py-1">Vercel</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <p className="pt-10 text-center text-4xl dark:text-white">
              Projects
            </p>
          </div>
          <div className="lg:flex gap-2">
            <div className="text-center shadow-lg p-10 rounded-xl dark:bg-blue-200 my-10 flex-1">
              <a
                href="https://github.com/Udokailodigwe/CountriesApp"
                target="_blank"
              >
                <Image
                  src={CountriesAppImage}
                  width={500}
                  height={500}
                  alt=""
                  style={{ margin: "auto" }}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Countries App
                </h3>
                <p className="py-3">
                  This is a Frontend application that displays the list of
                  countries all over the world. The app provides an opportuinity
                  for its user to add and delete countries on their favorite
                  page, view details of a single country, and sort countries
                  based on their population.
                </p>
                <h4 className="text-xl py-4 text-teal-600">Tools used</h4>
                <p className="text-gray-800 py-1">Typescript</p>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">Redux-Toolkit UI</p>
                <p className="text-gray-800 py-1">Material UI</p>
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl dark:bg-blue-200 my-10 flex-1">
              <a
                href="https://github.com/Udokailodigwe/e-commerce_fullstack_project"
                target="_blank"
              >
                <Image
                  src={ecommerce}
                  width={500}
                  height={500}
                  alt=""
                  style={{ margin: "auto" }}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Ecommerce App
                </h3>
                <p className="py-3">
                  This is a Full Stack application that provides an opportunity
                  to users to view list of clothes online. Users can add/remove
                  their favorite items in their cart, view more details on a
                  single cloth and also search for a product. Furthermore, this
                  application provides Google login authentication and an admin
                  dashboard page, where users and products can be managed.
                </p>
                <h4 className="text-xl py-4 text-teal-600">Tools used</h4>
                <p className="text-gray-800 py-1">Typescript</p>
                <p className="text-gray-800 py-1">React/React Native</p>
                <p className="text-gray-800 py-1">Redux Toolkit</p>
                <p className="text-gray-800 py-1">Node.js</p>
                <p className="text-gray-800 py-1">Express.js</p>
                <p className="text-gray-800 py-1">Google Auth</p>
                <p className="text-gray-800 py-1">Passport.js</p>
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl dark:bg-blue-200 my-10 flex-1">
              <a
                href="https://github.com/Udokailodigwe/memories-app-server"
                target="_blank"
              >
                <Image
                  src={memory}
                  width={500}
                  height={500}
                  alt=""
                  style={{ margin: "auto" }}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">Memory App</h3>
                <p className="py-3">
                  This application provide opportunity for people to upload and
                  share memories of themselves.
                </p>
                <h4 className="text-xl py-4 text-teal-600">Tools used</h4>
                <p className="text-gray-800 py-1">Javascript</p>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">Redux</p>
                <p className="text-gray-800 py-1">Node.js</p>
                <p className="text-gray-800 py-1">Express.js</p>
                <p className="text-gray-800 py-1">Material UI</p>
                <p className="text-gray-800 py-1">MongoDB</p>
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl dark:bg-blue-200 my-10 flex-1">
              <a
                href="https://github.com/Udokailodigwe/POKEDEX-App"
                target="_blank"
              >
                <Image
                  src={Pokemon}
                  width={500}
                  height={500}
                  alt=""
                  style={{ margin: "auto" }}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">Pokemon App</h3>
                <p className="py-3">
                  This is a simple application written with JavaScript, it
                  retrieves lists of pokemon from an external API. This
                  application enables the viewing of the Pokémons and details
                  about Pokémon on a modal view. It is further fleshed out with
                  Bootstrap for the client-view.
                </p>
                <h4 className=" text-xl selection:py-4 text-teal-600">
                  Tools used
                </h4>
                <p className="text-gray-800 py-1"></p>
                <p className="text-gray-800 py-1">HTML/CSS</p>
                <p className="text-gray-800 py-1">Javascript</p>
                <p className="text-gray-800 py-1">Bootstrap</p>
              </a>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl dark:bg-blue-200 my-10 flex-1">
              <a
                href="https://github.com/Udokailodigwe/chatMeUp"
                target="_blank"
              >
                <Image
                  src={chat}
                  width={500}
                  height={500}
                  alt=""
                  style={{ margin: "auto" }}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">ChatMeUp App</h3>
                <p className="py-3">
                  A React Native chat application for sending and recieving data
                  in real time. It offers multiple functionalities, such as
                  sending live location, taking photos and sending images. App
                  was built with Expo and Gifted Chat Library. App data is
                  stored using Firebase Cloud Storage.
                </p>
                <h4 className="text-xl py-4 text-teal-600">Tools used</h4>
                <p className="text-gray-800 py-1"></p>
                <p className="text-gray-800 py-1">React Native</p>
                <p className="text-gray-800 py-1">Expo</p>
                <p className="text-gray-800 py-1">Gifted Chat Library</p>
                <p className="text-gray-800 py-1">Firebase Cloud Storage</p>
              </a>
            </div>
          </div>
        </section>
        <footer>
          <p className="text-center dark:text-white">
            Designed and developed by Udodigwe Udoka
          </p>
          <p className="text-center italic dark:text-white">
            ilodigweudoka@gmail.com
          </p>
          <p className=" text-sm text-center italic dark:text-white">
            +358465931850
          </p>
          <div className="text-2xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/udoka-udodigwe-073872105/"
              target="_blank"
            >
              <AiFillLinkedin className="dark:text-white" />
            </a>
            <a
              href="https://www.instagram.com/skimmer_udy/?hl=en"
              target="_blank"
            >
              <AiFillInstagram className="dark:text-white" />
            </a>
            <a href="https://github.com/Udokailodigwe" target="_blank">
              <AiFillGithub className="dark:text-white" />
            </a>
          </div>
        </footer>
      </main>
    </div>
  );
}
